package ar.edu.utn.frre.cs.cuit;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Jun 15 17:12:03 ART 2012
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://cuit.cs.frre.utn.edu.ar/", name = "CuitValidationService")
@XmlSeeAlso({ObjectFactory.class})
public interface CuitValidationService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "validarCuit", targetNamespace = "http://cuit.cs.frre.utn.edu.ar/", className = "ar.edu.utn.frre.cs.cuit.ValidarCuit")
    @WebMethod
    @ResponseWrapper(localName = "validarCuitResponse", targetNamespace = "http://cuit.cs.frre.utn.edu.ar/", className = "ar.edu.utn.frre.cs.cuit.ValidarCuitResponse")
    public boolean validarCuit(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
