
/*
 * 
 */

package ar.edu.utn.frre.cs.cuit;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Jun 15 17:12:03 ART 2012
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "SimpleCuitValidatorImplService", 
                  wsdlLocation = "http://localhost:8080/frre-cs-cuit/SimpleCuitValidatorImpl?wsdl",
                  targetNamespace = "http://impl.cuit.cs.frre.utn.edu.ar/") 
public class SimpleCuitValidatorImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://impl.cuit.cs.frre.utn.edu.ar/", "SimpleCuitValidatorImplService");
    public final static QName SimpleCuitValidatorImplPort = new QName("http://impl.cuit.cs.frre.utn.edu.ar/", "SimpleCuitValidatorImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/frre-cs-cuit/SimpleCuitValidatorImpl?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/frre-cs-cuit/SimpleCuitValidatorImpl?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SimpleCuitValidatorImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SimpleCuitValidatorImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleCuitValidatorImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
//    public SimpleCuitValidatorImplService(WebServiceFeature ... features) {
//        super(WSDL_LOCATION, SERVICE, features);
//    }
//    public SimpleCuitValidatorImplService(URL wsdlLocation, WebServiceFeature ... features) {
//        super(wsdlLocation, SERVICE, features);
//    }
//
//    public SimpleCuitValidatorImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
//        super(wsdlLocation, serviceName, features);
//    }

    /**
     * 
     * @return
     *     returns CuitValidationService
     */
    @WebEndpoint(name = "SimpleCuitValidatorImplPort")
    public CuitValidationService getSimpleCuitValidatorImplPort() {
        return super.getPort(SimpleCuitValidatorImplPort, CuitValidationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CuitValidationService
     */
    @WebEndpoint(name = "SimpleCuitValidatorImplPort")
    public CuitValidationService getSimpleCuitValidatorImplPort(WebServiceFeature... features) {
        return super.getPort(SimpleCuitValidatorImplPort, CuitValidationService.class, features);
    }

}
